Workaround for Ruby 4.0+
ref. https://github.com/banister/binding_of_caller/pull/90

```
An error occurred while loading ./spec/parametarized_spec.rb.
Failure/Error: "integers"      | 1                     | 2                     | 3

 NoMethodError:
   undefined method 'of_caller' for an instance of Binding
 # ./vendor/bundle/ruby/4.0.0/gems/rspec-parameterized-table_syntax-2.0.1/lib/rspec/parameterized/table_syntax/table_syntax_implement.rb:6:in '|'
 # ./spec/parametarized_spec.rb:174:in 'block (4 levels) in <top (required)>'
 # ./vendor/bundle/ruby/4.0.0/gems/rspec-parameterized-core-2.0.1/lib/rspec/parameterized/core.rb:105:in 'BasicObject#instance_eval'
 # ./vendor/bundle/ruby/4.0.0/gems/rspec-parameterized-core-2.0.1/lib/rspec/parameterized/core.rb:105:in 'RSpec::Parameterized::Core::ExampleGroupMethods#define_cases'
 # ./vendor/bundle/ruby/4.0.0/gems/rspec-parameterized-core-2.0.1/lib/rspec/parameterized/core.rb:84:in 'RSpec::Parameterized::Core::ExampleGroupMethods#with_them'
 # ./spec/parametarized_spec.rb:180:in 'block (3 levels) in <top (required)>'
 # ./spec/parametarized_spec.rb:170:in 'block (2 levels) in <top (required)>'
 # ./spec/parametarized_spec.rb:134:in 'block in <top (required)>'
 # ./spec/parametarized_spec.rb:13:in '<top (required)>'
 Run options: include {current: true}
```