Fix build error with latest rake
last_comment is removed since rake 12.0.0

$ bundle exec rake
rake aborted!
NoMethodError: undefined method `last_comment' for #<Rake::Application:0x00000001b54158>
/home/travis/build/tomykaira/rspec-parameterized/gemfiles/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/rake_task.rb:82:in `define'
/home/travis/build/tomykaira/rspec-parameterized/gemfiles/vendor/bundle/ruby/2.2.0/gems/rspec-core-3.3.2/lib/rspec/core/rake_task.rb:62:in `initialize'
/home/travis/build/tomykaira/rspec-parameterized/Rakefile:7:in `new'
/home/travis/build/tomykaira/rspec-parameterized/Rakefile:7:in `<top (required)>'
/home/travis/build/tomykaira/rspec-parameterized/gemfiles/vendor/bundle/ruby/2.2.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)